name: Spaceship tests

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 8

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true

    - name: Set up Python
      run: uv python install 3.10

    - name: Install dependencies
      run: |
        uv sync --all-extras --dev

    - name: Test with pytest
      run: |
        uv run pytest -vv -p no:warnings
